## Driver Report, `r stage_code`  - `r driverCode`

```{r results='asis'}
if (driverCode %in% names(py$stage_txts))
  cat(paste('> ',py$stage_txts[[driverCode]]))
```

```{r driver-rebased-gap-{{result_group}}-{{stage_code}}-{{driverCodeClean}}, echo=FALSE, message=FALSE, error=FALSE, results='asis', cache=TRUE}
#driverCode="KAT"
driver_rebased_gap = group_stage_times %>%
                        #filter_at(vars(starts_with("split_")),
                        #          any_vars(! is.na(.))) %>% 
                          rebase( driverCode, rebase_cols,
                                  id_col='Code')

```



```{r}
# TO DO  - this should be in the thing that calls this template
driver_blank = driver_rebased_gap %>% filter(!is.na(Gap)) %>% plyr::empty()
```

  
`r ifelse(driver_blank, "No stage", "Stage")` report for `r driverCode`.

```{r driver-rebased-gap-{{result_group}}-{{stage_code}}-{{driverCodeClean}}-table, cache=TRUE}
if (!driver_blank){
  caption = paste0(stage_info_$code, ' stage report — ', driverCode, ' — ', rally_name)
  
  driver_rebased_gap %>%
    filter(!is.na(Gap)) %>%
    formattable(align='c',
                list(Gap = pm_color_bar2(),
                     entryId=FALSE), caption=caption)
}
```