```{r}
cat(paste("Enter driver_template", driverEntryId),
    file=logFile, sep='\n')
```

### Rebased Split Times

`r driverCode`'s delta at each split compared to other drivers.

```{r}
# Pass in driverId
driverCode = cars[cars$entryId==driverEntryId, 'code']
driver_rebased = rebase(full_splits_wide, driverCode,
                       split_names, id_col='code') %>%
                  select(code, all_of(split_names)) #%>%
                  #filter_at(vars(starts_with("split_")),
                  #              any_vars(! is.na(.)))

split_N_col_idx = which(colnames(driver_rebased) == 'split_N')[[1]]

caption = paste0(stage_info_$code, ' split delta (s) — ', driverCode, ' — ', rally_name)
#driver_rebased
```


```{r srt-{{result_group}}-{{stage_code}}-{{driverCodeClean}}, cache=TRUE}
# What is the color sence for the delta chartables
color_flip = FALSE
color_sense = c("green",'white',"red")

if (color_flip)
  color_sense = rev(color_sense)

# TO DO - with all_vars(! is.na(.)), if there is an NA we lose the column?
# CHECK
wide_splits_rebased = driver_rebased[,c('code',split_names)] %>%
                        filter_at(vars(starts_with("split_")),
                                    any_vars(! is.na(.)))  

# This errors if there is an NA? TO DO - black highlight?
if (color_flip)
  wide_splits_rebased = wide_splits_rebased %>% 
          #replace(is.na(.), 1e-9) %>%
          mutate_if(is.numeric, funs(. * -1))

wide_splits_rebased %>%
            formattable(align='c',
                    list(area(col = 2:split_N_col_idx) ~ color_tile2(color_sense),
                 entryId=FALSE), caption=caption )
#stop("TO HERE")
```

### Off-the-Pace Chart

Accumulated stage time deltas at each split:

```{r otp-chart-{{result_group}}-{{stage_code}}-{{driverCodeClean}}, cache=TRUE}
# TO DO
# the off_the_pace chart, and the simple max assignment, fail??
long_splits_rebased = wide_splits_rebased %>%
  pivot_longer(split_names,
                   names_to = "splitname",
                   values_to = "sectionDurationS") %>%
  merge(full_split_distances_df[,c('splitname','distance')],
         by='splitname')

zero_df = data.frame(code=unique(long_splits_rebased$code)) %>%
            mutate(distance=0, sectionDurationS=0, splitname = 'split_0')

long_splits_rebased = bind_rows(long_splits_rebased, zero_df)

g = long_splits_rebased %>%
        off_the_pace_chart(dist='distance',
                           t='sectionDurationS',
                           #label_typ='ggrepel',
                           code='code', yflip=TRUE) 
g + labs(title = paste0("Off-the-pace chart: ", 
                   driverCode, ', ', stage_info_$code),
  subtitle = paste("Time gained / lost over the stage",'—', rally_name),
  x="Distance into stage (km)",
  y="Time delta (s)",
  caption = "Created by: RallyDataJunkie" # eg WRC Rally

) 
``` 



### Within-Split Duration Deltas

`r driverCode`'s delta in time to complete each split section compared to other drivers:

```{r isdd-t-{{result_group}}-{{stage_code}}-{{driverCodeClean}}, cache=TRUE}
# Pass in driverId

driver_rebased = rebase(full_durations_wide, driverCode,
                       split_names, id_col='code') %>%
                  filter_at(vars(starts_with("split_")),
                                any_vars(! is.na(.)))

split_N_col_idx = which(colnames(driver_rebased) == 'split_N')[[1]]

caption = paste0(stage_info_$code, ' split section delta (s) — ', driverCode, ' - ', rally_name)
tmp_output_ = driver_rebased[,c('code',split_names)] %>%
                  filter_at(vars(starts_with("split_")),
                                any_vars(! is.na(.)))  %>%
  # Limit the decimal places displayed if we have near zero floating values
  mutate_if(is.numeric, round, digits = 1)

if (color_flip)
  tmp_output_ = tmp_output_ %>%
      # Change the numeric sense
      mutate_if(is.numeric, funs(. * -1))

tmp_output_ %>%
    formattable( align='c',
            list(area(col = 2:split_N_col_idx) ~ color_tile2(color_sense),
                 entryId=FALSE), caption=caption)
```

### Within-Split Pace Deltas

```{r spd-t-{{result_group}}-{{stage_code}}-{{driverCodeClean}}, cache=TRUE}
driver_rebased = rebase(section_pace_wide, driverCode,
                       split_names, id_col='code') %>%
                  select(code, all_of(split_names)) %>%
                  mutate_if(is.numeric, round, digits = 2)  #%>%
                  #filter_at(vars(starts_with("split_")),
                  #              any_vars(! is.na(.)))

split_N_col_idx = which(colnames(driver_rebased) == 'split_N')[[1]]

caption = paste0(stage_info_$code, ' split section pace delta (s/km) — ', driverCode, ' - ', rally_name)
driver_rebased_split_wide = driver_rebased[,c('code',split_names)] %>%
                  filter_at(vars(starts_with("split_")),
                                any_vars(! is.na(.)))  

if (color_flip)
  driver_rebased_split_wide = driver_rebased_split_wide %>%
            #replace(is.na(.), 1e-9) %>%
            mutate_if(is.numeric, funs(. * -1))

driver_rebased_split_wide %>%
            formattable(align='c',
                    list(area(col = 2:split_N_col_idx) ~ color_tile2(color_sense),
                 entryId=FALSE), caption=caption )
```

### Within-Split Pace Map

```{r pacemap-{{result_group}}-{{stage_code}}-{{driverCodeClean}}, cache=TRUE}
driver_pace_long_rebased = driver_rebased_split_wide %>% 
                gather(splitname, pace,
                       as.character(split_names)) %>%
                merge(full_split_distances_df[,c('splitname',
                                          'start_dist', 'distance')],
                      by='splitname')

driver_pace_long_rebased %>%
    pace_map( xstart='start_dist', id_col='code',
         xend='distance', lines=FALSE, label_dodge=2,
         label_size=2) + xlab("Accumulated stage distance (km)") + ylim(1.5, -1.5) + labs(title = paste0("Pace chart over splits — ", driverCode, ", ", stage_code),
  subtitle = paste0(rally_name),
  x="Distance into stage (km)",
  y="Pace delta (s/km)",
  caption = "Created by: RallyDataJunkie.com" ) 
```
```{r}
cat(paste("Leave driver_template", driverEntryId),
    file=logFile, sep='\n')
```
