```{r}
cat(paste("Enter overall_driver_template", driverCode),
    file=logFile, sep='\n')
```

## Driver Overall Report, `r driverCode` {-}

Rebased reports to end of `r last_stage_code`.


### Rebased Stage Times

`r driverCode`'s delta on each stage compared to other drivers.

```{r}

driver_blank = !(driverCode %in% multi_stage_times_wide$code)
```

`r ifelse(driver_blank, "No stage", "Stage")` report for `r driverCode`.

```{r overall-driver-stagedelta-{{last_stage_code}}-{{driverCodeClean}}, cache=FALSE}
if (!driver_blank){
  driver_rebased = rebase(multi_stage_times_wide, driverCode,
                       stage_codes, id_col='code') %>%
                  select(code, all_of(stage_codes)) #%>%
                  #filter_at(vars(starts_with("split_")),
                  #              any_vars(! is.na(.)))

last_col_idx = length(driver_rebased) #which(colnames(driver_rebased) == last_stage_code)[[1]]

  caption = paste0('Stage delta (s) — ', driverCode, ' — ', rally_name)
  
  
  # TO DO - If we have more than 10 columns this is too wide.
  # Need to group by every 10 columns via a template
  driver_rebased %>% 
    # Need to sort the table by overall leader
    # at end of last available stage
    dplyr::arrange(factor(code, levels = overall_order)) %>%
    mutate_if(is.numeric, round, digits = 1)  %>%
    formattable(align='c',
                      list(area(col = 2:last_col_idx) ~ color_tile2(c("green",'white',"red")),
                   entryId=FALSE), caption=caption )

}

# for each group of 10 or fewer cols, generate the table
# for i in ceiling(length(stage_codes)/10)
# get cols: code, then eg 2:11, 12:21, 22:24 
# max_val =  (i*10)+1
# max_val = ifelse(max_val>length(stage_codes),length(stage_codes), max_val )
# so (i-1)*10+2:maxval
```

*TO DO - the chart is not scrollable so we need to template the table to produce as many tables as required with 10 stage columns each.*
